import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      colorScheme: colorScheme,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.blue700,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              26,
            ),
          ),
          shadowColor: colorScheme.primary,
          elevation: 4,
        ),
      ),
      textTheme: TextTheme(
        headlineLarge: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: getFontSize(
            30,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        bodyLarge: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w300,
        ),
        titleMedium: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: getFontSize(
            17,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.gray50,
          fontSize: getFontSize(
            23,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Montserrat',
          fontWeight: FontWeight.w500,
        ),
        labelLarge: TextStyle(
          color: colorScheme.errorContainer,
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
      ),
      visualDensity: VisualDensity.standard,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    background: Color(0XFF07080A),
    error: Color(0XFF4C4C4C),
    errorContainer: Color(0XFFFFFFFF),
    inversePrimary: Color(0XFF07080A),
    inverseSurface: Color(0XFF4C4C4C),
    onBackground: Color(0XFF4C4C4C),
    onError: Color(0XFF07080A),
    onErrorContainer: Color(0XFF4C4C4C),
    onInverseSurface: Color(0XFF07080A),
    onPrimary: Color(0XFF4C4C4C),
    onPrimaryContainer: Color(0XFF4C4C4C),
    onSecondary: Color(0XFF4C4C4C),
    onSecondaryContainer: Color(0XFF07080A),
    onSurface: Color(0XFF4C4C4C),
    onSurfaceVariant: Color(0XFF07080A),
    onTertiary: Color(0XFF4C4C4C),
    onTertiaryContainer: Color(0XFF07080A),
    outline: Color(0XFF4C4C4C),
    //outlineVariant: Color(0XFF07080A),
    primary: Color(0X3F000000),
    primaryContainer: Color(0XFF07080A),
    //scrim: Color(0XFF07080A),
    secondary: Color(0XFF07080A),
    secondaryContainer: Color(0XFF4C4C4C),
    shadow: Color(0XFF4C4C4C),
    surface: Color(0XFF07080A),
    surfaceTint: Color(0XFF4C4C4C),
    surfaceVariant: Color(0XFF4C4C4C),
    tertiary: Color(0XFF07080A),
    tertiaryContainer: Color(0XFF4C4C4C),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amberA200 => Color(0XFFF9E144);
  // Black
  Color get black900 => Color(0XFF050214);
  // Blue
  Color get blue700 => Color(0XFF0163E0);
  // BlueGray
  Color get blueGray400 => Color(0XFF888888);
  // Gray
  Color get gray400 => Color(0XFFB4B4B4);
  Color get gray50 => Color(0XFFF8FAFF);
  Color get gray700 => Color(0XFF5C5A5A);
  // Pink
  Color get pink300 => Color(0XFFFF637D);
  // Red
  Color get red500 => Color(0XFFEB4335);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
